### ISSUE TITLE
Trying to upgrade from 1.1.7 

### ISSUE THREAD

**Issue by KonssnoK** [AArnott/ImmutableObjectGraph#112]
Hi there,
i'm new to the NuGet package system.

I'm trying to update a project made with version v1.1.7 (which had no dependencies)
to version 1.2.19 (which depends on roslyin), using VS2017.
At compile time the build fails because "dotnet codegen" cannot be found. (I installed .NET Core 2.1)

If i try to do 
`dotnet add package dotnet-codegen`
i get the error:
`error: Package dotnet-codegen 0.4.88 is not compatible with net461 (.NETFramework,Version=v4.6.1). Package dotnet-codegen 0.4.88 supports: netcoreapp2.0 (.NETCoreApp,Version=v2.0)
error: Package 'dotnet-codegen' is incompatible with 'all' frameworks in project 'C:\src\VSLua\src\LanguageModel\LanguageService.csproj'.`

The project with the v1.1.7 was made over .net45, not netcore. (but was not depend on roslyn though)

Any idea on how can i resolve?
Thanks!

**Comment by KonssnoK** [comment]
Actually i already tried that, but the result was not much different :)
I will investigate this error then:

`1>------ Rebuild All started: Project: LanguageService, Configuration: Debug Any CPU ------
1>  Unable to find deps.json generator project.
1>C:\Users\konss\.nuget\packages\codegeneration.roslyn.buildtime\0.4.88\build\CodeGeneration.Roslyn.BuildTime.targets(47,5): warning MSB3073: The command "dotnet codegen --version" exited with code 1.
1>  Unable to find deps.json generator project.
1>C:\Users\konss\.nuget\packages\codegeneration.roslyn.buildtime\0.4.88\build\CodeGeneration.Roslyn.BuildTime.targets(59,5): warning MSB3073: The command "dotnet codegen "@obj\Debug\LanguageService.csproj.dotnet-codegen.rsp"" exited with code 1.`

**Comment by KonssnoK** [comment]
I managed to proceed by changing the csproj file manually,
using 
`<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>`
instead of the old header. I still have a lot of things to see before compiling, but it's a step forward..!

**Comment by KonssnoK** [comment]
I managed to update completely the project.
Since it's yours (lol), if you wanna checkout the changes to build with 2017
https://github.com/KonssnoK/VSLua

I manage to install in VS2017, no idea if it works correctly though :)

**Comment by AArnott** [comment]
Nice. 
I set that repo up to capture work done by some interns at Microsoft. But I don't own it myself. 
I hope it works for you though. :)

**Comment by KonssnoK** [comment]
Seems to have some problem handling methods of classes (don't know if they are called that way in lua)

![image](https://user-images.githubusercontent.com/10288926/48808092-f54c7d80-ed1f-11e8-99fe-1c3168655e99.png)
