### ISSUE TITLE
Consider rearchitecting around custom SFG and Roslyn

### ISSUE THREAD

**Issue by AArnott** [AArnott/ImmutableObjectGraph#28]
Right now the system is based on T4, which is not only difficult to read but limits what kind of information we can use from the template source. We have an alternative to consider, as demo'd in [this video][1].

Please review and comment on this issue with your likes/dislikes.

 [1]: https://onedrive.live.com/redir?resid=63D0C265F96E43D!773501&authkey=!AIE3VOI9b7sN39c&ithint=video%2cwmv

**Comment by AArnott** [comment]
The new roslyn-based code gen has an SFG option as well as an MSBuild-based option. So you get to choose!

**Comment by IanYates** [comment]
Interesting - I'm really looking forward to playing with the Roslyn approach, although given I have about 100 T4 templates in my project using this library, and I've hacked lots of extra bits on to it, it will just be experimental for a while.  That, and VS 2015 is still crashing/freezing on me :( 

Still, the Rosyln approach has many benefits, which could only grow with time, and if I was coming to this project with fresh eyes I know I'd pick the Rosyln approach over T4 without much of a second thought :)

Quick question (which probably demonstrates my ignorance) - what does SFG stand for?  Single file generation?

**Comment by AArnott** [comment]
SFG=Single File Generator. It usually refers specifically to `IVsSingleFileGenerator` but is loosely used to refer to MSBuild targets that perform similar functions as well.

It's good to know you have an investment in the T4 templates. I was thinking of deleting them soon once the Roslyn ones have stabilized but maybe we'll keep them around for a while and take pull requests from you and others for a while yet.

FWIW, I `think` the roslyn approach will work on VS2013 too, since it just hooks into MSBuild. Yes, it has a VS2015-only VSIX SFG option, but I prefer the MSBuild one anyway.
