### ISSUE TITLE
Build after clean

### ISSUE THREAD

**Issue by MarkGodwin** [AArnott/ImmutableObjectGraph#29]
The workaround to avoid dependency problems in the .tt file works fine (i.e. get the project to compile once, then enable the .tt generation). However, when you clean the project, you end up in the same boat once again, as the bin directory is emptied.
If the assembly name references in the ImmutableObjectGraph.tt file are updated like this...:

    <#@ assembly name="$(SolutionDir)packages\Microsoft.Bcl.Immutable.1.0.34\lib\portable-net45+win8+wp8+wpa81\System.Collections.Immutable.dll" #>
    <#@ assembly name="$(SolutionDir)packages\ImmutableObjectGraph.Core.0.1.0-beta4\lib\portable-net45+win+wp80\ImmutableObjectGraph.dll" #>

Then the project builds fine, even with a full clean. If we could get the Nuget package install to re-write the references in the .tt file, it would be awesome.

Great work on the library, by the way. Any idea when this will be out of Beta?

**Comment by AArnott** [comment]
Thanks, @MarkGodwin. Is the `$(SolutionDir)` macro in your code snippet a literal of what should appear in the .tt file, or does it have to be expanded when the nuget package is installed?

The T4 templates will likely be removed soon. The Roslyn-based code generation approach is nearly complete as a replacement for the T4 templates.
