### ISSUE TITLE
Enhancement: Add support for transforming writeable properties to readonly properties

### ISSUE THREAD

**Issue by Lumirris** [AArnott/ImmutableObjectGraph#32]
Apologies if this was already requested and denied in another closed issue, but it would be nice to be able to transform this:

```c#
public class Fruit { string Color { get; set; } }
```
into this:
```c#
public class Fruit { 
    public Fruit(string color) {
        Color = color;
}
    public string Color { get; private set; }
}
```
It's simple enough to write the classes using only fields (no properties) as shown in the documentation if you know ahead of time that you want to use this library, but if you've already got more traditionally modeled classes written (say, ~400 of them), then it becomes another maddening task to convert them by hand (or maybe use another T4 template ;) to be transformed by this template.

I assume there's gotta be a good reason for only supporting fields currently. If there would be a lot of pain to implement what's described here, which you've already discovered, could you document it here in a comment? Otherwise, I think this would be very useful - as useful as the ability to reference classes in other files, which has already been requested.

**Comment by AArnott** [comment]
The T4 templates could certainly be modified to accept classes with mutable
auto-properties as input and still produce immutable classes as output.
However the T4 templates are about to be deleted in favor of using the
Roslyn code generation approach, which among other things satisfies the
other request you mentioned of being able to access other types defined in
the same project from within your immutable classes. So it sounds like the
most useful thing for you would be for a T4 template to migrate your old
auto-property code to the field code
You may want to take a look at Roslyn codegen approach also offered by this
library to understand the subtle differences between the input files so
that as you migrate your 400 classes to work with this tool that you do so
in a way that will work long term (via the Roslyn codegen approach using
the [GenerateImmutable] attribute).

How does that sound?

**Comment by Lumirris** [comment]
That sounds good. I hadn't seen any documentation in the README.md on the Roslyn codegen approach, so I forked the repository and started down a rabbit hole today (downloaded VS 2015 preview because the solution wouldn't load completely in VS 2013, etc.). I'm hoping that using Roslyn approach wouldn't preclude using this in projects targeting .NET 4.0. Fantastic work - kudos to you!

**Comment by AArnott** [comment]
Thanks. The Roslyn approach wouldn't preclude using the result in projects
targeting .NET 4.0, but the generated code's dependency on immutable
collections would. Both T4 and Roslyn code gen still use immutable
collections, and those are only available on .NET 4.5 and above.
If that's a serious adoption blocker we might be able to look for ways to
solve that.
