### ISSUE TITLE
Error generating code with nested classes inherited from a common base class

### ISSUE THREAD

**Issue by kevin1michael** [AArnott/ImmutableObjectGraph#40]
```csharp
using System.Collections.Immutable;
using ImmutableObjectGraph;
using ImmutableObjectGraph.CodeGeneration;

[GenerateImmutable]
public partial class SyntaxNode
{
    [Required]
    int startPosition;
    [Required]
    int length;
}

[GenerateImmutable]
public partial class ElseBlock : SyntaxNode
{
    [Required]
    readonly string elseKeyword;
}

[GenerateImmutable]
public partial class ElseIfBlock : SyntaxNode
{
    [Required]
    readonly string elseIfKeyword;
    [Required]
    readonly string thenKeyword;
}

[GenerateImmutable]
public partial class IfNode : SyntaxNode
{
    [Required]
    readonly string ifKeyword;
    [Required]
    readonly string thenKeyword;
    readonly ImmutableList<ElseIfBlock> elseIfList;
    readonly ElseBlock elseBlock;
    [Required]
    readonly string endKeyword;
}
```

ErrorCode: CS0122
Description: 'SyntaxNode.length' is inaccessible due to its protection level

Error Code: CS7036
Description: There is no argument given that corresponds to the required formal parameter 'identity' of 'SyntaxNode.SyntaxNode(uint, int, int, bool)'

**Comment by AArnott** [comment]
I've updated the repro code so that it compiles in isolation.

**Comment by AArnott** [comment]
@kevin1michael As a workaround, can you try adding this attribute to your `elseIfList` field?

    [NotRecursiveAttribute]

**Comment by kevin1michael** [comment]
@AArnott, that attribute doesnt seem to be identified... and I tried updating the nugget package too.

**Comment by AArnott** [comment]
Try pressing Ctrl+. on the line to see if you're missing a using directive.

**Comment by AArnott** [comment]
The test that repros this issue is in the `fix40` branch
