### ISSUE TITLE
With(...) method returns instance with the same Identity

### ISSUE THREAD

**Issue by edro** [AArnott/ImmutableObjectGraph#51]
With(...) method returns instance with the same Identity. Is this correct?
```
var mat1 = AffineTransform.Create();
var mat2 = mat1.With(c: 2);
Assert.That(mat1.GetHashCode(), Is.Not.EqualTo(mat2.GetHashCode()));
```
where my GetHasCode is:
```
public override int GetHashCode()
{
  return this.Identity.GetHashCode();
}
```

**Comment by AArnott** [comment]
Yes, that's by design. The point of the `Identity` property is to retain some recognition that one instance derived from another instance. If you want something that is distinct for every single instance, just use the instance itself rather than the `Identity` property.
Does that work for you?
