### ISSUE TITLE
"CreateWithIdentity" not generated on base class when derived class is in separate file

### ISSUE THREAD

**Issue by jviau** [AArnott/ImmutableObjectGraph#60]
Steps to reproduce:

##### A.cs
```C#
    [GenerateImmutable]
    public partial class A
    {
        readonly string field1;
    }
```

##### B.cs
```C#
    [GenerateImmutable]
    public partial class B : A
    {
        readonly string field2;
    }
```

This will produce an error where A.generated.cs does not have `CreateWithIdentity`, yet B.generated.cs will still try to call it in `ToA()`, causing an error.

Putting both `class A` and `class B` in the same file correctly generates the `CreateWithIdentity` method.

**Comment by AArnott** [comment]
Spreading type families across source files is not yet supported in general. 
Closing as a child of #61, which I filed to track the overall feature request.
