### ISSUE TITLE
Generate a public constructor with parameter names that match property names

### ISSUE THREAD

**Issue by AArnott** [AArnott/ImmutableObjectGraph#65]
In the interest of being compatible with the possibly upcoming C# future feature of records and the `with` keyword: https://github.com/dotnet/roslyn/issues/5172

This is expected to make deserialization logic of these generated types easier as well.

**Comment by AArnott** [comment]
I don't think we should do this issue for the sake of dotnet/roslyn#5172 until that feature is finalized.

@IanYates and @joeizy Can either of you confirm that a public constructor with parameters named after each property would be useful in deserialization code, and in particular, simpler than the Builder pattern mentioned in #42?

**Comment by joeizy** [comment]
If we're talking about manual deserialization it seems like that would be much easier as IanYates said in #42. I'm not sure that it affects automatic deserialization with something like JSON.NET or DataContractSerializer.

**Comment by AArnott** [comment]
I heard confirmed from someone (Jon Sequeira, actually) that Newtonsoft.Json will deserialize objects via their constructors if the ctor parameter names match the property names. So that's goodness.

**Comment by IanYates** [comment]
That's true.  I rely on that many times in our code for simple read-only DTO classes.

But now that I look for an authoritative source in the JSON.net docs I can't find where it really says that apart from reading the release notes where it gets smarter over time when handling constructors.  The tests at https://github.com/JamesNK/Newtonsoft.Json/blob/master/Src/Newtonsoft.Json.Tests/Serialization/ConstructorHandlingTests.cs go through the possibilities.
