### ISSUE TITLE
Dependency on CodeGeneration.Roslyn

### ISSUE THREAD

**Issue by azeno** [AArnott/ImmutableObjectGraph#72]
Just had a look at the latest version (1.1.69-beta-gba4e1c3e26) and noticed that installing ImmutableObjectGraph.Generation is not enough, one also needs to install the proper version of CodeGeneration.Roslyn in order for the code generator to kick in. Is this intentional? If so it should either get documented or the ImmutableObjectGraph.Generation package should depend on it.

**Comment by AArnott** [comment]
Thanks for the report. Yes, a package dependency is supposed to be there. I had tested it at one point but perhaps it regressed.
