### ISSUE TITLE
Question : What's the benefit of using SyntaxFactory instead of some DSL?

### ISSUE THREAD

**Issue by wallymathieu** [AArnott/ImmutableObjectGraph#74]
Good looking library!
We have been looking at the code and noticed heavy use of SyntaxFactory. As far as I understand, there is the CSharpSyntaxTree.ParseText ? Out of curiosity, why the extensive use of SyntaxFactory and not a DSL of your own?

**Comment by AArnott** [comment]
I might not fully appreciate what you're suggesting, so feel free to elaborate.
But we don't need a specialized language. C# is familiar to folks and adequate to minimally describe an immutable object. We generate C# code in order to compile partial classes together. A custom language would require a learning curve, and couldn't compile into the same assembly as the rest of the C# code.

**Comment by lgolding** [comment]
Hi Andrew and Wally,

I've written a similarly SyntaxFactory-heavy project recently (generates classes from a JSON schema) so I think I know what Wally is asking. For example, I have a method like this:

```C#
        private StatementSyntax MakeScalarHashCodeContribution(ExpressionSyntax expression)
        {
            return SyntaxFactory.ExpressionStatement(
                SyntaxFactory.AssignmentExpression(
                    SyntaxKind.SimpleAssignmentExpression,
                    SyntaxFactory.IdentifierName(GetHashCodeResultVariableName),
                        SyntaxFactory.BinaryExpression(
                            SyntaxKind.AddExpression,
                            SyntaxFactory.ParenthesizedExpression(
                                SyntaxFactory.BinaryExpression(
                                    SyntaxKind.MultiplyExpression,
                                    SyntaxFactory.IdentifierName(GetHashCodeResultVariableName),
                                    SyntaxFactory.LiteralExpression(
                                        SyntaxKind.NumericLiteralExpression,
                                        SyntaxFactory.Literal(GetHashCodeCombiningValue)))),
                            SyntaxFactory.InvocationExpression(
                                SyntaxFactory.MemberAccessExpression(
                                    SyntaxKind.SimpleMemberAccessExpression,
                                    expression,
                                    SyntaxFactory.IdentifierName(GetHashCodeMethod))))));
        }
```

... that generates a statement like this:

```C#
                result = (result * 31) + IntegerProp.GetHashCode();
```

... and the question is, why didn't I just write something like this:

```C#
        private StatementSyntax MakeScalarHashCodeContribution(ExpressionSyntax expression)
        {
            return CSharpSyntaxFactory.ParseText(
                $"{GetHashCodeResultVariableName} = ({GetHashCodeResultVariableName} * {GetHashCodeCombiningValue}) + {expression.ToString()}.GetHashCode()"); 
        }
```

(not sure if it's exactly right, but you get the idea).

In my case, the answer was "I didn't know about CSharpSyntaxFactory" (and also, I wanted to learn the Roslyn code generation APIs in detail).

As to the DSL question, I don't think Wally was asking "why didn't you invent a DSL for users to express their immutable classes"? I think he was asking "why didn't you invent a DSL to use in your implementation, to simplify the code?". For example, in my case, I might have (but did not think to) write a DSL so I could write something like this:

```C#
    MethodSyntax getHashCode = SyntaxFactory.Method("GetHashCode", ...);
    foreach (string propertyName in propertyNames)
    {
        getHashCode = getHashCode.WithScalarContributionFrom(propertyName);
    }
```

... that would call a method similar to above.

Those are nice ideas, Wally, thanks. I'll use them in my next big code gen project :-)

**Comment by AArnott** [comment]
I like to know what the syntax tree is that I'm constructing, since at various stages I have to modify it in ways ParseText doesn't cover.
