### ISSUE TITLE
Add hook for setter generation to enable INPC support on builders

### ISSUE THREAD

**Issue by eggapauli** [AArnott/ImmutableObjectGraph#78]
We would like to use immutable objects for our application pipeline but when creating forms we need a mutable wrapper. Currently we write out mutable classes so.

    public class Person : ReactiveObject {

        public string Name {
                get{ return _Name; }
                set{ this.RaiseAndSetIfChanged(ref _Name, value); }
        }
    }

Now we can bind to Person in a WPF form. Would it be possible to have a hook that generates application specific setters for the builders and be able to specify a base class for the builder? This would simplify our application greatly.

Then again if you could just have a flag that generates INPC support for the builders then that would be great.

**Comment by AArnott** [comment]
I think adding `INotifyPropertyChanged` support to the Builders would be a good idea, and simpler than adding an extensibility point.

**Comment by eggapauli** [comment]
We also thought about creating a custom implementation of [ICodeGenerator](https://github.com/AArnott/CodeGeneration.Roslyn/blob/master/src/CodeGeneration.Roslyn/ICodeGenerator.cs). We quickly read through the [source code](https://github.com/AArnott/CodeGeneration.Roslyn/blob/919cd298c2a6dbe7a7e53ce593553880055bded3/src/CodeGeneration.Roslyn/DocumentTransform.cs#L51) of how generators are applied and we don't think that a generator can take the output of a previous generator as input, right? They seem to only be able to generate new types.

**Comment by AArnott** [comment]
That's right. But the use case of building a chain of generators that modify the output of the previous one is certainly interesting.
Feel free to file an issue suggesting that on the other project.
In the meantime, I probably won't have time to make the INPC enhancement to this project within the next month, but a PR is something I could likely review and accept if you submit one.

**Comment by eggapauli** [comment]
I tried setting up the project for the last 3 hours and I just can't get it to build. I get all sorts of build errors that are coming from `NuProj` or `NuSpec.ReferenceGenerator`. So for now we stop working on this. I hope I can come back to it again. Thanks for your help so far.

**Comment by AArnott** [comment]
"nuget restore src" at the root of the repo followed by a build of the solution (as you can find in the appveyor.yml file) should be sufficient.
NuSpec.ReferenceGenerator can sometimes cause build failures, which I tend to resolve by doing a `git clean -fdx :/` then starting over with nuget restore then build.

**Comment by eggapauli** [comment]
Thanks. I followed the [guide](https://github.com/AArnott/ImmutableObjectGraph/blob/master/CONTRIBUTING.md) you provide. From the command line I get the following error:

```
"C:\Users\egger\Workspace\ImmutableObjectGraph\src\ImmutableObjectGraph.sln" (default target) (1) ->
"C:\Users\egger\Workspace\ImmutableObjectGraph\src\ImmutableObjectGraph.Core.NuGet\ImmutableObjectGraph.Core.NuGet.nupr
oj" (default target) (3) ->
(CreatePackage target) ->
  C:\Users\egger\.nuget\packages\NuProj\0.10.48-beta-gea4a31bbc5\tools\NuProj.targets(525,5): error : The replacement t
oken 'GitCommitIdShort' has no value. [C:\Users\egger\Workspace\ImmutableObjectGraph\src\ImmutableObjectGraph.Core.NuGe
t\ImmutableObjectGraph.Core.NuGet.nuproj]
```

When I open the solution in Visual Studio the references don't work (I think this is related to https://github.com/NuGet/Home/issues/1831)

Can you build the project using VS? Or do you work from the command line?

**Comment by AArnott** [comment]
I use VS. But as VS's built-in package restore tends to be rather buggy, I turn off package restore on build in VS and run it from the command line instead.
You must use [nuget 3.3.0](https://dist.nuget.org/win-x86-commandline/v3.3.0/nuget.exe) for this operation because newer versions are buggy.

**Comment by eggapauli** [comment]
Ahh I see, I used 3.4.4. Thanks for the help. I'll see if I can come back to it. Seems to be some very interesting projects you have here.

**Comment by AArnott** [comment]
I found some time to work on this, and have it nearly done. I just need to add some tests.

**Comment by AArnott** [comment]
@eggapauli Can you take a look at the PR and tell me if it suits your needs? 

The setter now looks like this (for a property called `PathSegment`):

```csharp
if (this.pathSegment != value)
{
    this.pathSegment = value;
    this.OnPropertyChanged();
}
```
