### ISSUE TITLE
Is it possible to target .Net standard rather than portable?

### ISSUE THREAD

**Issue by bradphelan** [AArnott/ImmutableObjectGraph#87]
https://oren.codes/2016/06/23/portable-is-dead-long-live-netstandard/

**Comment by bradphelan** [comment]
I can't use System.Interactive as it no longer support PCL profiles.

**Comment by azeno** [comment]
Any news on this? Would be nice to see ImmutableObjectGraph working with .netstandard

**Comment by AArnott** [comment]
I am trying very hard to refresh this repo to work with the latest tooling, including supporting .NET Standard. I'm really struggling to get assembly loads to work over in the dependency project CodeGeneration.Roslyn. Once I get that working, I should be able to complete the change to this project.

**Comment by azeno** [comment]
Sorry for bothering again but are the required changes done in CodeGeneration.Roslyn?

**Comment by AArnott** [comment]
I'm looking again at this today. I don't know if all the prereq work is done, but I'll try to find out.

**Comment by azeno** [comment]
Just to let you know I've started working on this and will do a PR soon. We have quite some troubles with a dependency conflict on System.Collections.Immutable so this is kind of pressing for us.

**Comment by AArnott** [comment]
Great. I really appreciate that. It's a tricky thing to get right with all dependencies, I know.

**Comment by AArnott** [comment]
I just pushed my `vs2017` branch where my work toward this goal is. Please build on it if you can, since it renovates the repo significantly for leverage VS2017 features like .NET SDK projects.

**Comment by AArnott** [comment]
Fixed by 2d6a1b83cf2c29937464e48dbaff44d82ce532d7.
