### ISSUE TITLE
Can the readonly ImmutableList properties take part in DataContract serialization?

### ISSUE THREAD

**Issue by PradeepKadubandi** [AArnott/ImmutableObjectGraph#92]
It seems no and I just want to confirm and see if there are alternatives... (I can think of ugly alternatives and want to check if I am missing any simpler ones)...

The problem is this, If I have a class like this:

```
[DataContract]
public class MyClass
{
    [DataMember]
    readonly ImmutableList<AnotherDataContractType> myProperty;
}
```

I see that generated code contains MyProperty as a get only property and even though the constructor had an Obsolete attribute saying that it exists for serializers to work, the above seems to fail to deserialize the collection (I am guessing that it's because DataContract serialization does not support ImmutableCollection semantics).

If I have the MyProperty as a private settable property, I could provide a[ [OnSerializedAttribute] ](https://msdn.microsoft.com/en-us/library/system.runtime.serialization.onserializedattribute(v=vs.110).aspx) and [OnDeserializedAttribute] method implementations and set the property for serialization to work.

Is there any simpler way that I can choose when I am using this template?

**Comment by AArnott** [comment]
The DataContractSerializer doesn't support immutable collections, as you've surmised. But [Json.NET and protobuf do](https://www.infoq.com/news/2013/11/Serialization-Immutable). Are either of those options for you?

See also [other issues discussing deserialization](https://github.com/AArnott/ImmutableObjectGraph/issues?utf8=%E2%9C%93&q=serialization)

**Comment by PradeepKadubandi** [comment]
Thanks for the confirmation and pointers to previous discussions... they were useful... Yeah I was planning to investigate using Json.NET ...
